name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        include:
          #          - platform: macos-latest
          #            arch: x64
          - platform: macos-latest
            arch: arm64
    #          - platform: ubuntu-latest
    #            arch: x64
    #          - platform: ubuntu-latest
    #            arch: arm64
    #          - platform: ubuntu-latest
    #            arch: arm
    #          - platform: windows-latest
    #            arch: x64
    
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: 'true'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.0.x

      - name: Build
        env:
          os: ${{ runner.os == 'Windows' && 'win' || runner.os == 'macOS' && 'osx' || 'linux' }}
        run: dotnet publish -c Release -r ${{ env.os }}-${{ matrix.arch }} -p:ImportByWildcardBeforeSolution=false -p:PublishSingleFile=true -o build

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: AvaloniaTAS-${{ runner.os == 'Windows' && 'win' || runner.os == 'macOS' && 'osx' || 'linux' }}-${{ matrix.arch }}
          path: build/**/*
