name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'

      - name: Install dependencies
        run: dotnet restore
      - name: Publish Windows
        run: dotnet publish -r win-x64 --self-contained=false /p:PublishSingleFile=true --output ./publish-win-x64
      - name: Publish Linux
        run: dotnet publish -r linux-x64 --self-contained=false /p:PublishSingleFile=true --output ./publish-linux-x64
      - name: Publish MacOS
        run: dotnet publish -r osx-x64 --self-contained=false /p:PublishSingleFile=true --output ./publish-osx-x64
      
      - name: Upload Windows
        uses: actions/upload-artifact@v2
        with:
          name: AvaloniaTAS-win-x64
          path: publish-win-x64/**/*
      - name: Upload Linux
        uses: actions/upload-artifact@v2
        with:
          name: AvaloniaTAS-linux-x64
          path: publish-linux-x64/**/*
      - name: Upload MacOS
        uses: actions/upload-artifact@v2
        with:
          name: AvaloniaTAS-osx-x64
          path: publish-osx-x64/**/*
